on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n kbalphaweb -g kbalphaweb9bae-rg --location "South Africa North" --sku Basic --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n kbalphaweb --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n kbalphaweb --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n kbalphaweb --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: kbalphaweb.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t kbalphaweb.azurecr.io/kbalphaqa:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push kbalphaweb.azurecr.io/kbalphaqa:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_kbalphaqa_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep kb_alpha_qa9ffa | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace kb_alpha_qa9ffa`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: kb_alpha_qa9ffa
        container-registry-url: kbalphaweb.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: kbalphaqadockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: kb_alpha_qa9ffa
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          kbalphaweb.azurecr.io/kbalphaqa:${{ github.sha }}
        imagepullsecrets: |
          kbalphaqadockerauth   
