name: "build-test"
on: [push]

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: |
        npm install -g newman
        npm install -g newman-reporter-htmlextra
        npm run all
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    
    - name: Run Newman
      uses: ./      
      id: run-api-tests
      with:
        apiKey: ${{ secrets.POSTMAN_API_KEY }}
        collection: ${{ secrets.POSTMAN_COLLECTION_ID }}
        environment: ${{ secrets.POSTMAN_ENVIRONMENT }}
        reporters: cli

    - name: Run Newman - Failure Continue
      uses: ./      
      id: run-api-tests-failure
      with:
        apiKey: ${{ secrets.POSTMAN_API_KEY }}
        collection: ${{ secrets.POSTMAN_COLLECTION_ID }}
        environment: ${{ secrets.POSTMAN_ENVIRONMENT }}
        reporters: cli
        suppressExitCode: "true"
    
    - name: Export Summary from Outputs
      run: |
        echo ${{ steps.run-api-tests.outputs.summary }}
